INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE) VALUES ('example@Gmail.com', '123456', 'USER', 'CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE) VALUES ('example2@Gmail.com', '123456', 'ADMIN', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE) VALUES ('example3@Gmail.com', '123456', 'USER', 'CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE) VALUES ('example4@Gmail.com', '123456', 'MANAGER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE) VALUES ('5@Gmail.com', '123456', 'USER', 'BANNED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE) VALUES ('example4@Gmail.com', '123456', 'MANAGER', 'NOT_CONFIRMED');
